const farmingMethodsNames = [
  "Organic Farming",
  "Conventional Farming",
  "Sustainable Farming",
  "Permaculture",
  "Hydroponics",
  "Aquaponics",
  "Agroforestry",
  "No-Till Farming",
  "Biodynamic Farming",
  "Vertical Farming",
  "Intensive Farming",
  "Dryland Farming",
  "Shifting Cultivation",
  "Integrated Pest Management (IPM)",
  "Community Supported Agriculture (CSA)",
  "Fallow Farming",
  "Mixed Farming",
  "Crop Rotation",
  "Agroecology",
  "Precision Agriculture",
];

const pesticides = [
  "Insecticides",
  "Herbicides",
  "Fungicides",
  "Rodenticides",
  "Bactericides",
  "Nematicides",
  "Acaricides",
  "Growth Regulators",
  "Contact Pesticides",
  "Systemic Pesticides",
  "Biopesticides",
  "Organic Pesticides",
  "Neonicotinoids",
  "Chlorinated Hydrocarbons",
  "Phosphates",
  "Pyrethroids",
  "Natural Pesticides",
];

const irrigationMethods = [
  "Surface Irrigation",
  "Drip Irrigation",
  "Sprinkler Irrigation",
  "Subsurface Irrigation",
  "Flood Irrigation",
  "Trickle Irrigation",
  "Basin Irrigation",
  "Micro Irrigation",
  "Center Pivot Irrigation",
  "Manual Irrigation",
  "Tidal Irrigation",
  "Bubbler Irrigation",
  "Aeroponic Irrigation",
  "Spray Irrigation",
  "Contour Irrigation",
  "Zai Pits",
  "Rainfed Irrigation",
];

const soilTypes = [
  "Clay",
  "Sandy",
  "Silt",
  "Loamy",
  "Peaty",
  "Saline",
  "Chalky",
  "Alluvial",
  "Laterite",
  "Podzol",
  "Black Soil",
  "Red Soil",
  "Yellow Soil",
  "Desert Soil",
  "Salty Soil",
  "Rocky Soil",
  "Volcanic Soil",
  "Humic Soil",
  "Marl",
  "Organic Soil",
];


export {soilTypes, farmingMethodsNames, irrigationMethods, pesticides}
